version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${MY_PORT}
    container_name: deno-chat-nvc-telegram-bot
    image: deno-chat-nvc-telegram-bot-image
    ports:
      - "${MY_PORT}:${MY_PORT}"