version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    container_name: deno-chat-nvc-telegram-bot
    image: deno-chat-nvc-telegram-bot-image
    ports:
      - "${PORT}:${PORT}"